allowBuilds:
  better-sqlite3: true
  es5-ext: true
  esbuild: true
  vue-demi: true
  workerd: true

packages:
  - '.'

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260813.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260813.1'
  - '@cloudflare/workerd-linux-64@1.20260813.1'
  - '@cloudflare/workerd-linux-arm64@1.20260813.1'
  - '@cloudflare/workerd-windows-64@1.20260813.1'
  - '@cloudflare/workers-types@5.20260813.1'
  - workerd@1.20260813.1
